# TODO: add configuration parameters here

URL_SCHEME = 'url'
URL_SCHEME_WITH_SEPARATOR = URL_SCHEME + '://'

WINDOW_TITLE = 'My GUI'

INITIAL_WINDOW_WIDTH = 1024
INITIAL_WINDOW_HEIGHT = 768

APPLICATION_NAME = "pytabs"
APPLICATION_CONFIG_FILE_LOCATION = "." + APPLICATION_NAME.lower()